ORB_FEATURES = 1000

ESSENTIAL_RANSAC_THRESHOLD = 1.0

PNP_MIN_POINTS = 15
PNP_MIN_INLIERS = 12
PNP_REPROJECTION_ERROR = 12.0

LOCAL_MAP_RECENT_KEYFRAMES = 10
LOCAL_MAP_FALLBACK_POINTS = 3000

TRACKING_SEARCH_RADIUS = 40
TRACKING_DESCRIPTOR_THRESHOLD = 50

MAX_TRIANGULATION_DEPTH = 100

KEYFRAME_TRANSLATION_THRESHOLD = 10
KEYFRAME_ROTATION_THRESHOLD = 0.6
KEYFRAME_NEW_POINTS_RATIO = 0.5
KEYFRAME_MIN_MAP_POINTS_FOR_NEW_POINTS_RATIO = 200

# MapPoint culling
CULLING_ENABLED = True
CULLING_EVERY_KEYFRAMES = 5

CULLING_MIN_OBSERVATIONS = 2
CULLING_MIN_UNIQUE_KEYFRAMES = 2
CULLING_MAX_REPROJECTION_ERROR = 20.0

CULLING_MIN_MAP_POINTS = 1000
CULLING_MIN_AGE_KEYFRAMES = 3